export const STANDARD_REPLACER_CHANGE_ACTIVE =
	'STANDARD_REPLACER_CHANGE_ACTIVE';

export const CUSTOM_REPLACER_CHANGE_ACTIVE = 'CUSTOM_REPLACER_CHANGE_ACTIVE';
export const CUSTOM_REPLACER_REMOVE = 'CUSTOM_REPLACER_REMOVE';
export const CUSTOM_REPLACER_CREATE = 'CUSTOM_REPLACER_CREATE';
export const CUSTOM_REPLACER_CHANGE_DATA = 'CUSTOM_REPLACER_CHANGE_DATA';
